spring:
  datasource:
    username: USER
    password: PASSWORD  
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//127.0.0.1:1521/XE
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect  
    hibernate:
      ddl-auto: none
    show-sql: true