spring:
  datasource:
    username: sa
    password: password  
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./DB_H2/biblioteca
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true